### ISSUE TITLE
Case #3 is generating an error

### ISSUE THREAD

**Issue by dldyment** [kohlgjh/PHYS449-Project-Group6#1]
exact error:
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main(args)
  File "main.py", line 45, in main
    rwnn_obj_vals, rwnn_cross_vals = rwnn.train_and_test()
  File "C:\Users\delan\OneDrive - University of Waterloo (1)\Undergrad\4A\PHYS449\Github\PHYS449-Project-Group6\src\model\RWNN.py", line 109, in train_and_test
    obj_val = self.loss_fct(self.model.forward(self.train_input[iteration]), self.train_target[iteration])
  File "C:\Users\delan\OneDrive - University of Waterloo (1)\Undergrad\4A\PHYS449\Github\PHYS449-Project-Group6\src\model\model.py", line 24, in forward
    x = self.input_layer(x)
  File "C:\Users\delan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\delan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (81x42 and 44x12)

**Comment by kohlgjh** [comment]
Fixed this. Incorrect number of input neurons in the params.json (42) when it needed to be 44
